// Textos EN/ES de /actinver y /portfolio (y sus gemelas en español). Van aquí
// y no en ui.ts porque son párrafos largos de dos secciones, como ya hace
// src/i18n/research.ts con los suyos.
//
// LÍMITE DE AUTORÍA: en este archivo NO hay una sola frase sobre ninguna
// empresa ni sobre ninguna posición. Solo se describe la página, de dónde sale
// cada número y qué significa. La tesis y el riesgo de cada posición los
// escribe Jaime en src/data/actinver.json y src/data/portfolio.json.
import type { Locale } from './routes';

const en = {
  // ---- Etiquetas compartidas por las dos páginas ----
  lbl: {
    summary: 'Where it stands',
    value: 'Portfolio value',
    valueNote: 'cash plus open positions',
    valueNoteNoCash: 'what the open positions are worth',
    change: 'Change since the start',
    changeNote: 'against the starting capital',
    changeNoteCost: 'against what the positions cost',
    best: 'Best position',
    worst: 'Worst position',
    onlyOne: 'Only one position so far, so best and worst are the same one.',
    trades: 'Trades',
    tradesNote: 'one buy per position, plus one sell per position closed',
    cash: 'Cash left',
    realized: 'Realised on closed positions',
    capital: 'Starting capital',
    capitalPending: 'not set yet',
    positions: 'Positions',
    open: 'Open',
    closed: 'Closed',
    entry: 'Bought',
    exit: 'Sold',
    qty: 'Shares',
    cost: 'Cost',
    price: 'Price now',
    marketValue: 'Value',
    weight: 'Weight',
    pl: 'Gain / loss',
    thesis: 'Why I bought it',
    risk: 'What can go wrong',
    noPrice: 'No automatic price for this ticker: the figures below are the ones I wrote down.',
    missing: 'Waiting on the price of {tickers}, so there is no total yet.',
    atClose: 'Figures at the close of {date}, from the snapshot in the repository. They refresh with delayed prices as soon as this page loads.',
    live: 'Prices from {source}, delayed at least {delay} minutes and cached for another minute. They update when you open or reload the page, not continuously.',
    chart: 'How it has moved',
    chartNote: 'One point per trading day, written into the repository by a scheduled job after the close. The line does not depend on anything being alive when you read this.',
    chartEmpty: 'The chart appears once there are two nights of history.',
    chartAria: 'Portfolio value, one point per trading day',
    chartStart: 'Start',
    chartLatest: 'Latest',
    chartBase: 'Starting capital',
    inSpanish: 'Jaime wrote this in Spanish and it has not been translated yet.',
    updated: 'Positions last edited by hand on {date}.',
    source: 'Yahoo Finance',
    howH: 'How this page is built',
    how: [
      'The positions live in a JSON file in the public repository. Jaime edits it by hand and writes the thesis and the risk himself; nothing here is generated by AI.',
      'The file is checked against a schema on every build. A missing date, a price that is not a number or a closed position without an exit price stops the deploy instead of publishing a wrong figure.',
      'Prices come from the site\'s own endpoint, which reads Yahoo Finance and caches it. They are delayed, and the page says by how much right next to the figures.',
      'Every trading night a scheduled job works out what the portfolio is worth and writes one line into the repository. That file, and nothing else, is what the chart draws.'
    ],
    repo: 'See the file on GitHub',
    exampleH: 'What a position looks like',
    exampleNote: 'This is the documented example inside the file — not a real position. It is checked by the same schema as the real ones, so it can be copied as it is.',
    methodology: 'Full site methodology',
    assetPage: 'Open the asset page',
    homeH: 'My portfolios',
    homeOpen: 'See the positions'
  },

  actinver: {
    title: 'Actinver Challenge: my positions and the reason for each one — Smart Finance',
    desc: 'My portfolio in the Actinver Challenge, a student stock-market contest played with fictional money: every position with the thesis behind it, the main risk, and a value snapshot taken every trading night.',
    eyebrow: 'Actinver Challenge 2026',
    h1: 'The Actinver Challenge, position by position',
    lede: 'A student stock-market contest, played with fictional money. I publish every position with the reason I opened it, before knowing whether it worked out.',
    warnH: 'This is a simulator',
    warn: 'The Actinver Challenge is a contest for students. The money is fictional: no shares were bought or sold, no account exists and nothing here can be cashed in. It is published because the point of the contest is to think out loud, and a thesis written after the fact is worth nothing.',
    datesH: 'The dates',
    dates: {
      practice: 'Practice round',
      real: 'The contest itself',
      ends: 'It ends on'
    },
    emptyH: 'No positions yet',
    emptyLede: 'The contest starts on 5 October 2026. Until the first buy, this page has nothing to show — and it says so instead of filling the space.',
    emptyList: [
      'Each position with the shares, the price paid and the date.',
      'The thesis: one or two sentences on why I bought it, written before the result is known.',
      'The main risk of that position, in my own words.',
      'The value of the portfolio, the change against the starting capital, and the best and worst position.',
      'A chart built from one snapshot per trading night.'
    ],
    rulesH: 'What I am holding myself to',
    rules: [
      'The thesis goes up when the position is opened, not once it is clear whether it worked.',
      'A position that loses money stays on the page, with its exit price and its date.',
      'The figures are the ones the file holds. If a price is missing, the page says so instead of guessing.',
      'When the contest ends on 13 November, the post-mortem goes here: what I got right, what I got wrong and what I would not do again.'
    ],
    discH: 'Educational, not advice',
    disc: 'This is a student playing a contest with fictional money and publishing his reasoning to learn in the open. It is not financial, investment or tax advice, and it is not a recommendation to buy or sell anything. The prices come from Yahoo Finance with a delay, and the contest platform may value the portfolio differently. A company can appear both here and in my research; when that happens, the interest is disclosed on both pages.',
    otherLink: 'My personal portfolio, with real money'
  },

  portfolio: {
    title: 'My portfolio: the positions and the thesis behind each one — Smart Finance',
    desc: 'The positions I hold with my own money, each with the thesis I wrote when I opened it and the main risk. Published for educational purposes: it is not a recommendation.',
    eyebrow: 'Portfolio',
    h1: 'What I own, and why',
    lede: 'My own positions, with real money and in the open. Each one carries the reason I opened it, written before knowing how it would go, and the risk I think it has.',
    warnH: 'Positions, not recommendations',
    warn: 'These are personal positions, published so the reasoning can be read and argued with. They are not advice and not a recommendation to buy or sell anything. What is on this page is the positions I publish, each with its thesis and its weight: the total is what those positions are worth, not my savings and not a statement of net worth.',
    emptyH: 'Nothing published yet',
    emptyLede: 'There are no positions on this page yet. It goes up when there is a position with a thesis worth reading, not before.',
    emptyList: [
      'Each position with its shares, the price paid and the date.',
      'The thesis: one or two sentences on why I bought it.',
      'The main risk of that position.',
      'What the positions are worth today, with delayed prices.',
      'A chart built from one snapshot per trading night.'
    ],
    rulesH: 'What I am holding myself to',
    rules: [
      'The thesis goes up when the position is opened, and it is not edited afterwards to look smarter.',
      'A position that loses money stays on the page, with its exit price and its date.',
      'If a company on this page also appears in my research, both pages say so.',
      'Every position on this page carries its thesis, its size and its weight. What is not published is my account balance, and this page is not a statement of net worth.'
    ],
    discH: 'Educational, not advice',
    disc: 'I am a student publishing my own positions to learn in the open. This is not financial, investment or tax advice, and it is not a recommendation to buy or sell anything. I hold the positions listed here, so read them as what they are: an interested party\'s opinion, with the interest declared. Prices come from Yahoo Finance with a delay and can be wrong; check them at the source before deciding anything.',
    otherLink: 'My Actinver Challenge portfolio (fictional money)'
  }
};

const es: typeof en = {
  lbl: {
    summary: 'Cómo va',
    value: 'Valor de la cartera',
    valueNote: 'efectivo más posiciones abiertas',
    valueNoteNoCash: 'lo que valen las posiciones abiertas',
    change: 'Variación desde el inicio',
    changeNote: 'contra el capital inicial',
    changeNoteCost: 'contra lo que costaron las posiciones',
    best: 'Mejor posición',
    worst: 'Peor posición',
    onlyOne: 'Por ahora hay una sola posición, así que la mejor y la peor son la misma.',
    trades: 'Operaciones',
    tradesNote: 'una compra por posición, más una venta por cada posición cerrada',
    cash: 'Efectivo',
    realized: 'Realizado en lo cerrado',
    capital: 'Capital inicial',
    capitalPending: 'todavía sin definir',
    positions: 'Posiciones',
    open: 'Abierta',
    closed: 'Cerrada',
    entry: 'Compra',
    exit: 'Venta',
    qty: 'Títulos',
    cost: 'Costo',
    price: 'Precio ahora',
    marketValue: 'Valor',
    weight: 'Peso',
    pl: 'Ganancia / pérdida',
    thesis: 'Por qué la compré',
    risk: 'Qué puede salir mal',
    noPrice: 'Este ticker no tiene precio automático: las cifras de abajo son las que anoté yo.',
    missing: 'Falta el precio de {tickers}, así que todavía no hay total.',
    atClose: 'Cifras al cierre del {date}, de la foto guardada en el repositorio. Se actualizan con precios retrasados en cuanto carga la página.',
    live: 'Precios de {source}, con al menos {delay} minutos de retraso y un minuto más de caché. Se actualizan cuando abres o recargas la página, no de forma continua.',
    chart: 'Cómo se ha movido',
    chartNote: 'Un punto por día hábil, escrito en el repositorio por una tarea programada después del cierre. La línea no depende de que nada esté vivo cuando la lees.',
    chartEmpty: 'La gráfica aparece cuando haya dos noches de historial.',
    chartAria: 'Valor de la cartera, un punto por día hábil',
    chartStart: 'Inicio',
    chartLatest: 'Último',
    chartBase: 'Capital inicial',
    inSpanish: 'Jaime escribió esto en español y todavía no está traducido.',
    updated: 'Posiciones editadas a mano por última vez el {date}.',
    source: 'Yahoo Finance',
    howH: 'Cómo está hecha esta página',
    how: [
      'Las posiciones viven en un archivo JSON del repositorio público. Jaime lo edita a mano y escribe él la tesis y el riesgo; aquí no hay texto generado por IA.',
      'El archivo se valida contra un esquema en cada build. Una fecha que falta, un precio que no es número o una posición cerrada sin precio de salida paran el despliegue en vez de publicar una cifra mal.',
      'Los precios salen del propio endpoint del sitio, que lee Yahoo Finance y lo cachea. Van retrasados, y la página dice cuánto justo al lado de las cifras.',
      'Cada noche hábil, una tarea programada calcula cuánto vale la cartera y escribe una línea en el repositorio. Esa línea, y nada más, es lo que dibuja la gráfica.'
    ],
    repo: 'Ver el archivo en GitHub',
    exampleH: 'Cómo se ve una posición',
    exampleNote: 'Este es el ejemplo documentado dentro del archivo, no una posición real. Lo valida el mismo esquema que a las de verdad, así que se puede copiar tal cual.',
    methodology: 'Metodología completa del sitio',
    assetPage: 'Ver la ficha del activo',
    homeH: 'Mis carteras',
    homeOpen: 'Ver las posiciones'
  },

  actinver: {
    title: 'Reto Actinver: mis posiciones y la razón de cada una — Smart Finance',
    desc: 'Mi cartera del Reto Actinver, un concurso estudiantil de bolsa que se juega con dinero ficticio: cada posición con su tesis, el riesgo principal y una foto del valor cada noche hábil.',
    eyebrow: 'Reto Actinver 2026',
    h1: 'El Reto Actinver, posición por posición',
    lede: 'Un concurso de bolsa para estudiantes que se juega con dinero ficticio. Publico cada posición con la razón por la que la abrí, antes de saber si salió bien.',
    warnH: 'Esto es un simulador',
    warn: 'El Reto Actinver es un concurso para estudiantes. El dinero es ficticio: no se compró ni se vendió ninguna acción, no hay ninguna cuenta detrás y nada de esto se puede cobrar. Se publica porque la gracia del concurso es pensar en voz alta, y una tesis escrita después no vale nada.',
    datesH: 'Las fechas',
    dates: {
      practice: 'Prácticas',
      real: 'El reto de verdad',
      ends: 'Termina el'
    },
    emptyH: 'Todavía no hay posiciones',
    emptyLede: 'El reto empieza el 5 de octubre de 2026. Hasta la primera compra, esta página no tiene nada que enseñar, y lo dice en vez de rellenar el hueco.',
    emptyList: [
      'Cada posición con los títulos, el precio pagado y la fecha.',
      'La tesis: una o dos frases sobre por qué la compré, escritas antes de saber el resultado.',
      'El riesgo principal de esa posición, con mis palabras.',
      'El valor de la cartera, la variación contra el capital inicial y la mejor y la peor posición.',
      'Una gráfica hecha con una foto por noche hábil.'
    ],
    rulesH: 'A qué me obligo',
    rules: [
      'La tesis se publica al abrir la posición, no cuando ya se sabe si funcionó.',
      'Una posición que pierde se queda en la página, con su precio de salida y su fecha.',
      'Las cifras son las que dice el archivo. Si falta un precio, la página lo dice en vez de adivinar.',
      'Cuando el reto termine, el 13 de noviembre, aquí va el post-mortem: qué acerté, qué fallé y qué no volvería a hacer.'
    ],
    discH: 'Educativo, no es asesoría',
    disc: 'Esto es un estudiante jugando un concurso con dinero ficticio y publicando su razonamiento para aprender en público. No es asesoría financiera, de inversión ni fiscal, y no es una recomendación de comprar o vender nada. Los precios vienen de Yahoo Finance con retraso, y la plataforma del concurso puede valuar la cartera de otra forma. Una empresa puede aparecer aquí y en mi research a la vez; cuando pasa, el interés se declara en las dos páginas.',
    otherLink: 'Mi portafolio personal, con dinero real'
  },

  portfolio: {
    title: 'Mi portafolio: las posiciones y la tesis de cada una — Smart Finance',
    desc: 'Las posiciones que tengo con mi propio dinero, cada una con la tesis que escribí al abrirla y el riesgo principal. Se publica con fines educativos: no es una recomendación.',
    eyebrow: 'Portafolio',
    h1: 'Qué tengo, y por qué',
    lede: 'Mis propias posiciones, con dinero real y a la vista. Cada una lleva la razón por la que la abrí, escrita antes de saber cómo iba a salir, y el riesgo que creo que tiene.',
    warnH: 'Posiciones, no recomendaciones',
    warn: 'Son posiciones personales, publicadas para que se pueda leer y discutir el razonamiento. No son asesoría ni una recomendación de comprar o vender nada. Lo que hay en esta página son las posiciones que publico, cada una con su tesis y su peso: el total es lo que valen esas posiciones, no mis ahorros ni una declaración de patrimonio.',
    emptyH: 'Todavía no hay nada publicado',
    emptyLede: 'Aún no hay posiciones en esta página. Sube cuando haya una posición con una tesis que valga la pena leer, no antes.',
    emptyList: [
      'Cada posición con sus títulos, el precio pagado y la fecha.',
      'La tesis: una o dos frases sobre por qué la compré.',
      'El riesgo principal de esa posición.',
      'Cuánto valen hoy las posiciones, con precios retrasados.',
      'Una gráfica hecha con una foto por noche hábil.'
    ],
    rulesH: 'A qué me obligo',
    rules: [
      'La tesis se publica al abrir la posición, y después no se edita para parecer más listo.',
      'Una posición que pierde se queda en la página, con su precio de salida y su fecha.',
      'Si una empresa de esta página también sale en mi research, las dos páginas lo dicen.',
      'Cada posición de esta página lleva su tesis, su tamaño y su peso. Lo que no se publica es el saldo de la cuenta, y esta página no es una declaración de patrimonio.'
    ],
    discH: 'Educativo, no es asesoría',
    disc: 'Soy un estudiante publicando sus propias posiciones para aprender en público. Esto no es asesoría financiera, de inversión ni fiscal, y no es una recomendación de comprar o vender nada. Tengo las posiciones que aparecen aquí, así que léelas por lo que son: la opinión de una parte interesada, con el interés declarado. Los precios vienen de Yahoo Finance con retraso y pueden estar mal; compruébalos en la fuente antes de decidir nada.',
    otherLink: 'Mi cartera del Reto Actinver (dinero ficticio)'
  }
};

export const cartera = { en, es } as const;
export function useC(locale: Locale) { return cartera[locale]; }
export type CarteraCopy = typeof en;
